version: '3.7'
services:
  apollo-configservice:
    network_mode: host
    restart: always
    image: apolloconfig/apollo-configservice:1.8.1
    container_name: apollo-configservice
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.86.128:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    volumes:
      - /tmp/logs:/opt/logs

  apollo-adminservice:
    network_mode: host
    depends_on:
      - apollo-configservice
    restart: always
    image: apolloconfig/apollo-adminservice:1.8.1
    container_name: apollo-adminservice
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.86.128:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    volumes:
      - /tmp/logs:/opt/logs

  apollo-portal:
    network_mode: host
    depends_on:
      - apollo-adminservice
    restart: always
    image: apolloconfig/apollo-portal:1.8.1
    container_name: apollo-portal
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.86.128:3306/ApolloPortalDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      APOLLO_PORTAL_ENVS: dev
      DEV_META: http://192.168.86.128:8080
    volumes:
      - /tmp/logs:/opt/logs



